# Generated by Django 2.2.27 on 2022-03-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220308_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='attachment',
        ),
        migrations.AddField(
            model_name='sample',
            name='name',
            field=models.CharField(default='user', max_length=24),
        ),
    ]
