name: Docker Image CI

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
    - name: Docker build
      run : docker build . -t djsmanoj/cbe1:latest
    - name: Docker Push
      run: docker push djsmanoj/cbe1:latest
